<a href="https://colab.research.google.com/github/ucfilho/Codigos_Teste/blob/master/FAOptim_fev_10_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from random import randint

In [0]:
'''Rosembrock Function'''
def Fun(x):
    fun=0
    a=1.0
    b=100.0
    fun = (a-x[0])**2 + b*(x[1]-x[0]**2)**2
    return fun

In [0]:
''' 
FOBJ gera vetorialmente os valores com a funcao objetivo escalar
em outras palavras gera para populacao o valor da funcao 
a ser otimizada
'''
def FOBJ(X):
    rows = X.shape[0]
    fobj=np.zeros(rows)
    for i in range(rows):
        fobj[i]=Fun(X[i,])
    return fobj

In [0]:
'''Enxame retorna a populacao aleatoria com todos valores entre MIN e MAX'''
def Enxame(PAR,NPAR,MAX,MIN):
    x=np.zeros((NPAR, len(MAX)))
    for j in range(len(MAX)):
        for i in range(NPAR):
            x[i,j]=MIN[j]+(MAX[j]-MIN[j])*np.random.random()
    return x

In [0]:
'''
Obtem a melhor escolha
'''
def GetBest(x,xbest):
    ycal=FOBJ(x)
    #ycal=Fun(x)
    best=np.argmin(ycal)
    yref=Fun(xbest)
    if(yref<ycal[best]):
        GBEST=xbest
    else:
        GBEST=x[best,]
    return GBEST
    

In [20]:
cols=2
rows=10
ve=[3.1415,2.7182]#np.array()
A=np.repeat(ve, rows).reshape((cols,rows)).T
print(A)

[[3.1415 2.7182]
 [3.1415 2.7182]
 [3.1415 2.7182]
 [3.1415 2.7182]
 [3.1415 2.7182]
 [3.1415 2.7182]
 [3.1415 2.7182]
 [3.1415 2.7182]
 [3.1415 2.7182]
 [3.1415 2.7182]]


In [0]:
'''
Calcula a norma entre os vetores (distancia entre os fireflies)
'''

def Rij(xi,xj):
  cols=x1.shape[1]
  rows=x1.shape[0]
  Norma=np.zeros(rows) # inicializa o vertor norma
  x=xi-xj
  for i in range(rows):
    vector=x[i,]
    for j in range(cols):
      rij=np.sqrt(sum(j**2 for j in vector))
    Norma[i]=rij
  return Norma
    

In [8]:
# atualiza a populacao de firefly
def New_X(X,index,MAX,MIN,Beta,Gama):
  i=index
  rows=X.shape[0]
  cols=X.shape[1]
  xnew=np.zeros((rows,cols))
  vetor=X[i, ] # np.array()
  A=np.repeat(vetor, rows).reshape((cols,rows)).T
  Norma=Rij(X,A)
  Fobj=FOBJ(X)
  Epson=Enxame(cols,rows,MAX,MIN) # posicao aleatoria q entra na correcao
        #Enxame(PAR,NPAR,MAX,MIN):
  xi=X[i,]
  Fobj_i=Fobj(i)
  for j in range(rows):
    rij=Norma[j]
    xj=X[j,]
    novo=0
    if(Fobj(i)> Fobj(j)):
      Alfa=np.random.random()
      xi=xi+Beta*np.exp(-Gama*rij**2)*(xj-xi)+Alfa*Epson[j,]
      X[i,]=xi
      Fobj_i=Fobj(j))
    else
  return xnew

'# atualiza a populacao de firefly\ndef New_X(X,X0,MAX,MIN,Beta,Gama):\n  xnew=[]\n  rij=Rij(X,X0)\n  PAR=len(X)\n  Epson=Enxame(PAR,1,MAX,MIN)[0,] # posicao aleatoria q entra na correcao\n  Alfa=np.random.random()\n  xnew=X+Beta*np.exp(-Gama*rij**2)*(X0-X)+Alfa*Epson\n  return xnew'

In [9]:
'''import numpy as np
PAR=2 #NUM DE PARAMETROS A SER OTIMIZADOS
MAX=[2,2] # MAXIMO DE CADA PARAMETRO
MIN=[-2,-2] # MINIMO DE CADA PARAMETRO
Beta=2.5
Gama=1.5
x1 = np.array([1,2])
x2= np.array([2,3])
rij=Rij(x1,x2)
print(rij)
x=New_X(x1,x2,MAX,MIN,Beta,Gama)
print(x)
xbest=GetBest(x1,x2)
print(xbest)'''

'import numpy as np\nPAR=2 #NUM DE PARAMETROS A SER OTIMIZADOS\nMAX=[2,2] # MAXIMO DE CADA PARAMETRO\nMIN=[-2,-2] # MINIMO DE CADA PARAMETRO\nBeta=2.5\nGama=1.5\nx1 = np.array([1,2])\nx2= np.array([2,3])\nrij=Rij(x1,x2)\nprint(rij)\nx=New_X(x1,x2,MAX,MIN,Beta,Gama)\nprint(x)\nxbest=GetBest(x1,x2)\nprint(xbest)'

In [0]:

'''
Metodo firefly

'''
def FAOPtim(ITE,PAR,Beta,Gama,NPAR,MAX,MIN):

    xbest=Enxame(PAR,1,MAX,MIN)[0,] #inicializa xbest
    xo=Enxame(PAR,NPAR,MAX,MIN) # inicializa os fireflies...
    vbest_old=Fun(xbest)
    vbest_new=Fun(xbest)
    x=[] # populacao do enxame q vai ser atualizada
    
    for k in range(ITE):
      ycal=FOBJ(xo)
      for i in range(PAR):
        for j in range(PAR):
          if(ycal[i]>ycal[j]):
            x=New_X(x,xo,MAX,MIN,Beta,Gama)
          else:
            x=xo[j,]
            
          xbest=GetBest(x,xo)
          return xbest  

In [11]:
NPAR=10 #PARTICULAS
ITE=300 #ITERACOES
PAR=2 #NUM DE PARAMETROS A SER OTIMIZADOS
MAX=[2,2] # MAXIMO DE CADA PARAMETRO
MIN=[-2,-2] # MINIMO DE CADA PARAMETRO
Beta=2.5
Gama=1.5
x1=Enxame(PAR,NPAR,MAX,MIN)
x2=Enxame(PAR,NPAR,MAX,MIN)
print(x2)
print(x1)
Norma=Rij(x1,x2)
print(Norma)
fobj=FOBJ(x1)
print(fobj)
best=GetBest(x1,x1[0,])
print(best)
'''
for i in range(6):
    print("resolucao",i+1," ")
    xbest=FAOPtim(ITE,PAR,Beta,Gama,NPAR,MAX,MIN)
    print("vetor",xbest,"funcao", Fun(xbest),"\n")'''

[[-1.84850794  1.16052789]
 [-0.04136892 -0.76603372]
 [-1.0851236  -1.25036158]
 [ 0.85847748  1.45491615]
 [-1.790264   -1.43730038]
 [ 0.56556192 -1.80153002]
 [-1.88134241 -0.35863381]
 [ 0.58385712 -1.19766154]
 [ 1.95803173  1.79884749]
 [-0.61421351  0.22274584]]
[[ 1.95828838  0.82895237]
 [ 1.01027299  0.85630535]
 [-0.24901533 -1.82481282]
 [-0.92578261 -1.32025562]
 [-0.88953954  1.90693234]
 [-1.0436846  -1.013277  ]
 [ 1.30478845  0.70088222]
 [-0.16142289  0.51176946]
 [ 0.3972564   1.46763353]
 [ 1.54631292 -0.17306211]]
[3.8212093  1.93337394 1.0144315  3.29926696 3.4634083  1.79193113
 3.35767838 1.86483153 1.59553199 2.19648319]
[904.48644276   2.70107162 357.56956148 477.78482534 128.03824292
 446.25020554 100.41128773  24.94052879 171.9263738  657.78280305]
[1.01027299 0.85630535]


'\nfor i in range(6):\n    print("resolucao",i+1," ")\n    xbest=FAOPtim(ITE,PAR,Beta,Gama,NPAR,MAX,MIN)\n    print("vetor",xbest,"funcao", Fun(xbest),"\n")'